Renamed some variable to pihole-manager and made installing a little more simple.

diff --git a/src/pihole-manager b/src/pihole-manager
--- a/src/pihole-manager
+++ b/src/pihole-manager
@@ -24,7 +24,7 @@ function __root_check () {
 
 	# Some commands require root access in order to function propertly. Only
 	# those that require well check for permissions.
-	! test "${EUID}" -eq "0" && echo "root premission required!" && exit 1
+	! test "$(id -u)" -eq "0" && echo "root premission required!" && exit 1
 
 }
 
@@ -34,7 +34,7 @@ function __health_check () {
 	# If Pihole is running normally do nothing.
 	if test "$(pihole status | grep 'Pihole blocking is disabled')" ||
 	   test "$(pihole status | grep 'DNS service is NOT running')"; then
-		echo "(${__name} Error) not enabled - $(date -R)" >> ${__logging}
+		echo "(${program_name} Error) not enabled - $(date -R)" >> ${log_out}
 		pihole enable & sleep 5s && exit 1
 	fi
 
@@ -44,7 +44,7 @@ function __pihole_gravity () {
 
 	# Update the gravity and sleep at the sametime for 10s.
 	if pihole updateGravity > /dev/null & sleep 10s ; then
-		echo "(${__name}) Gravity Updated - $(date -R)" >> ${__logging}
+		echo "(${program_name}) Gravity Updated - $(date -R)" >> ${log_out}
 	fi
 
 }
@@ -62,35 +62,35 @@ function __pihole_firmware () {
 
 		# Update and sleep for 90 seconds at the sametime.
 		if pihole updatePihole > /dev/null & sleep 90s ; then
-			echo "(${__name}) Updated - $(date -R)" >> ${__logging}
+			echo "(${program_name}) Updated - $(date -R)" >> ${log_out}
 			reboot
 		fi
 
 	# If Pihole is up-to-date, then simply log that it is.
 	elif test "${__current}" = "${__latest}" ; then
-		echo "(${__name}) Update to date - $(date -R)" >> ${__logging}
+		echo "(${program_name}) Update to date - $(date -R)" >> ${log_out}
 	fi
 
 }
 
 set -e
 
-__name="pihole-manager"
+program_name="pihole-manager"
 
-__logging="/var/log/pihole-manager.log"		# Log every this script does.
+log_out="/var/log/pihole-manager.log"		# Log every this script does.
 
 # Basic info
-__info=$(cat <<EOF
-${__name} - version (${version})
+about=$(cat <<EOF
+${program_name} - version (${version})
 EOF
 )
 
 # The help and basic info.
-__help=$(cat <<EOF
-${info}
+usage=$(cat <<EOF
+${about}
 
-usage: ${__name} command
-usage: ${__name} command <option>
+usage: ${program_name} command
+usage: ${program_name} command <option>
 
 commands
 
@@ -111,46 +111,47 @@ options
 
 	--all			Update firmware and gravity.
 
-pihole-server-updater homepage: <https://www.github.com/mschaecher78/pihole-server-updater/>
+pihole-server-updater homepage: <https://www.github.com/mschaecher78/pihole-manager/>
 Copyright (C) 2021 <Michael L. Schaecher> MIT License
 EOF
 )
 
-test ! -f ${__logging} && touch ${__logging}				# Create log file if it does not exit.
+test ! -f ${log_out} && touch ${log_out}			# Create log file if it does not exit.
 
 while true ; do case "${1}" in
 	flush)
-		! __root_check && exit 1				# Exit if fails.
-		__health_check && shift 1				# shift one space over if health check passes.
+		! __root_check && exit 1			# Exit if fails.
+		__health_check && shift 1			# shift one space over if health check passes.
 
 		# If any one of the commands fail then error and exit dirty.
 		if pihole flush && pihole arpflush  ; then
-			echo "(Pihole) logs flushed             - $(date -R)" >> ${__logging}
+			echo "(Pihole) logs flushed             - $(date -R)" >> ${log_out}
 			break
 		else
-			echo "(Pihole) Error: log flushed       - $(date -R)" >> ${__logging}
+			echo "(Pihole) Error: log flushed       - $(date -R)" >> ${log_out}
 			exit 1
 		fi
 
 	;;
 	log)
-		cat "${__logging}" | less && break			# # Display log file using less command.
+		cat "${log_out}" | less && break		# # Display log file using less command.
 	;;
 	help)
-		echo "${__help}" && break				# Helpful tips
+		echo "${usage}" && break			# Helpful tips
 	;;
 	update)
-		! __root_check && exit 1				# Exit if fails.
-		__health_check && shift 1				# shift one space over if health check passes.
+		! __root_check && exit 1			# Exit if fails.
+		__health_check && shift 1			# shift one space over if health check passes.
 	;;
-	version)	echo "${__info}" && break			# Display name and version info
+	version)
+		echo "${about}" && break			# Display name and version info
 	;;
 	--gravity)
 		# The Pihole Gravity is really just a custom /etc/hosts file that redirects websites
 		# that are listed to "0.0.0.0" which is, in a way a blackhole. Causing everything listed
 		# to be sucked down into nothing.
 		if ! __pihole_gravity ; then
-			echo "(Pihole) Error: gravity update   - $(date -R)" >> ${__logging}
+			echo "(Pihole) Error: gravity update   - $(date -R)" >> ${log_out}
 			exit 1
 		fi
 
@@ -160,7 +161,7 @@ while true ; do case "${1}" in
 		# Lets just hope that this doesn't happen, but if the command does fail log and
 		# exit with error. Otherwise nothing to see here.
 		if ! __pihole_firmware ; then
-			echo "(Pihole) Error: firmware update  - $(date -R)" >> ${__logging}
+			echo "(Pihole) Error: firmware update  - $(date -R)" >> ${log_out}
 			exit 1
 		fi
 
@@ -172,11 +173,11 @@ while true ; do case "${1}" in
 		# If the first command completes without a hitch then move on to the next command.
 		# Now if any one of the commands fail, exit with an error.
 		if ! __pihole_gravity ; then
-			echo "(Pihole) Error: gravity update - $(date -R)" >> ${__logging}
+			echo "(Pihole) Error: gravity update - $(date -R)" >> ${log_out}
 			exit 1
 		else
 			if ! __pihole_firmware ; then
-				echo "(Pihole) Error: firmware update - $(date -R)" >> ${__logging}
+				echo "(Pihole) Error: firmware update - $(date -R)" >> ${log_out}
 				exit 1
 			fi
 		fi
@@ -184,7 +185,7 @@ while true ; do case "${1}" in
 		break
 	;;
 	*)
-		echo "${__name} invalid command or option!" && exit 1	# Exit if ivalid command/option
+		echo "${program_name} invalid command or option!" && exit 1	# Exit if ivalid command/option
 	;;
 esac done
 
